IMAGE_NAME = "bento/ubuntu-20.04"

Vagrant.configure("2") do |config|
    config.vm.box = IMAGE_NAME
    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "basebox.yml"
    end
end
