IMAGE_NAME = "nconnolly1/windows-2019-sds"
SSV_DIR = ENV['TMP'] + "/SANsymphony"
NSSV = 2
NHOST = 1

Vagrant.configure(2) do |config|
	config.vm.box = IMAGE_NAME
	config.vm.guest = :windows
	config.vm.communicator = "winrm"
	config.vm.boot_timeout = 300
	config.vm.network :forwarded_port, guest: 3389, host: 3389, id: 'rdp', auto_correct: true
	config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.synced_folder SSV_DIR, "/install",
        type: "smb", smb_username: 'vagrant', smb_password: 'vagrant'

    config.vm.provider "hyperv" do |v|
        config.vm.network "private_network", bridge: "NATSwitch"
        v.enable_virtualization_extensions = true
		v.ip_address_timeout = 240
        v.linked_clone = true
    end

    (1..NSSV).each do |i|
        config.vm.define "ssv-#{i}" do |node|
            node.vm.provider "hyperv" do |v|
                v.mac = "00155D0052#{i + 30}"
                v.memory = 4096
                v.cpus = 4
            end

            node.vm.network "private_network", ip: "192.168.50.#{i + 30}"
            node.vm.hostname = "node-#{i}"

            if i == NSSV
                node.vm.provision "ansible" do |ansible|
                    ansible.limit = "ssv-*"
                    ansible.playbook = "ssv.yml"
                    ansible.become_user = "vagrant"
                end
            end
        end
    end

	(1..NHOST).each do |i|
        config.vm.define "host-#{i}" do |node|
            node.vm.provider "hyperv" do |v|
                v.mac = "00155D0052#{i + 40}"
                v.memory = 4096
                v.cpus = 2
            end

            node.vm.synced_folder ".", "/vagrant", disabled: true 
            node.vm.network "private_network", ip: "192.168.50.#{i + 40}"
            node.vm.hostname = "node-#{i}"
        end
    end
end
