IMAGE_NAME = "nconnolly1/ubuntu-20.04-k8s"
N = 1

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    config.vm.provider "hyperv" do |v|
        config.vm.network "private_network", bridge: "NATSwitch"
        v.enable_virtualization_extensions = true
        v.linked_clone = true
        v.memory = 8192
        v.cpus = 4
    end

    (1..N).each do |i|
        config.vm.define "swarm-#{i}" do |node|
            node.vm.provider "hyperv" do |v|
                v.mac = "00155D0052#{i + 50}"
            end

            node.vm.box = IMAGE_NAME
            node.vm.network "private_network", ip: "192.168.50.#{i + 50}"
            node.vm.hostname = "swarm-#{i}"
            node.vm.synced_folder ".", "/vagrant", disabled: true
        end
    end
end
