Vagrant.configure(2) do |config|
  config.vm.box = "nconnolly1/windows-2019"
  config.vm.guest = :windows
  config.vm.communicator = "winrm"
  config.vm.boot_timeout = 300
  config.vm.network :forwarded_port, guest: 3389, host: 3389, id: 'rdp', auto_correct: true
  config.vm.synced_folder ".", "/vagrant", disabled: true 

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "sds.yml"
    ansible.become_user = "vagrant"
  end
end
