Vagrant.configure(2) do |config|
  config.vm.box = "nconnolly1/windows-2019"
  config.vm.guest = :windows
  config.vm.communicator = "winrm"
  config.vm.boot_timeout = 300
  config.vm.network :forwarded_port, guest: 3389, host: 3389, id: 'rdp', auto_correct: true
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = 1024
  end

  config.vm.provider 'hyperv' do |hv|
    config.vm.network "private_network", bridge: "NATSwitch"
    hv.ip_address_timeout = 240
    hv.memory = 1024
    hv.linked_clone = true
  end

  config.vm.provider :libvirt do |domain|
    domain.memory = 2028
    domain.cpus = 2
  end
end
